backend/api/urls.py
from django.urls import path
from api import views

urlpatterns = [
    path('',views.LandingView.as_view(),name='landing'),
    path('',views.IndexView.as_view(),name='index'),
    path('signup/',views.signup,name="create_user"),
    path('login/',views.user_login,name='login'),
    path('collegelist/',views.CollegeListView.as_view(),name="all_college"),
    path('logout/',views.user_logout,name="logout"),
    path('dataExtract/',views.dataextract,name="data_extra"),
    path('collegeTour/',views.collegeTourView,name="tour_college"),
    path('college/<int:pk>',views.CollegeDetailView.as_view(),name="detail_college"),
    path('chatbot/',views.ChatbotView.as_view(),name="chatbot_help"),
    # path('',views.LandingView.as_view(),name='landing'),

]

backend/backend/urls.py
from django.contrib import admin
from django.urls import path
from api import views
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/',include('api.urls')),

]

backend/api/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse_lazy,reverse
import pgeocode
import math
nomi = pgeocode.Nominatim('in')



class StudentModel(models.Model):
    user = models.OneToOneField(User,related_name="user_profile",on_delete=models.CASCADE,null=True,blank=True)
    percentile = models.FloatField(default=0.00)
    address = models.TextField()
    pincode = models.IntegerField(default=0)

    # def __str__(self):
    #     return self.user.email


class CollegeModel(models.Model):
    name = models.CharField(max_length=50)
    address = models.TextField()
    cutoff = models.FloatField(default=0.00)
    pincode = models.IntegerField(default=0)
    distance = models.IntegerField(default=0)
    nirf = models.IntegerField(default=0)
    fee = models.IntegerField(default=0)
    hostel = models.BooleanField(default=False)
    website = models.TextField(default="")
    salary = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    def updateDistance(self,myPin):
        srcPinLoc = nomi.query_postal_code(str(myPin))
        srcLat = srcPinLoc.latitude
        srcLong = srcPinLoc.longitude

        destPinLoc = nomi.query_postal_code(str(self.pincode))
        destLat = destPinLoc.latitude
        destLong = destPinLoc.longitude


        R = 6373.0
        lat1 = math.radians(srcLat)
        lon1 = math.radians(srcLong)
        lat2 = math.radians(destLat)
        lon2 = math.radians(destLong)
        dlon = lon2 - lon1
        dlat = lat2 - lat1
        a = math.sin(dlat / 2)**2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2)**2
        c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
        self.distance = R * c






        # self.distance = 
        #calculate distance
        self.save()

class PdfModel(models.Model):
    pdf = models.FileField(null = True,blank=True,upload_to='pdfs')

    def __str__(self):
        return self.pdf.url

backend/api/forms.py
from django import forms
from django.contrib.auth.models import User
from api.models import StudentModel,CollegeModel,PdfModel

class studentForm(forms.ModelForm):
    password  = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','password','email')

class studentExtraForm(forms.ModelForm):
    class Meta():
        model = StudentModel
        fields = ('percentile','address','pincode',)


class collegeForm(forms.ModelForm):
    class Meta():
        model = CollegeModel
        fields = '__all__'
    
    

class PdfForm(forms.ModelForm):
    class Meta():
        model = PdfModel
        fields = '__all__'

backend/api/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView, ListView, DetailView
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse_lazy, reverse
from api.forms import PdfForm,studentExtraForm,studentForm,collegeForm
from api.models import StudentModel,CollegeModel,PdfModel
from django.contrib.auth.decorators import login_required
from pathlib import Path



# Create your views here.
# import pgeocode
# nomi = pgeocode.Nominatim('in')
# print(nomi.query_postal_code("401303").latitude)

import fitz

# idx == 11 for name
# idx == 105[2] for percentile

# print(text[11])
# print(text[105][15:])

# print(text)


class LandingView(TemplateView):
    template_name = "landing.html"


class IndexView(TemplateView):
    template_name = "index.html"

def join_in(request):
    
    return render(request, "join.html")


def signup(request):
    upload_form = PdfForm()

    # print("signup")
    registered = False

    userval = ""
    fullnameval = ""
    percentileval = ""


    # print(request.FILES)

    if 'pdf' in request.FILES and request.method == 'POST':
        print("Uploaded")

        pdfnew = PdfModel()
        pdfnew.pdf = request.FILES['pdf']
        pdfnew.save()

        BASE_DIR = Path(__file__).resolve().parent.parent
        file_path = str(BASE_DIR)+str(pdfnew.pdf.url)

        print(file_path)

        doc = fitz.Document(file_path) 
        page = doc[0]
        print(page.get_text())

        text = page.get_text().split('\n')
        userval = text[11]
        fullnameval = text[11]
        percentileval =  (text[105][15:])        
        upload_form = PdfForm()
        student_form=studentForm()
        student_extra_form = studentExtraForm()

        # print(text[11])
        # print(text[105][15:])

    elif request.method == 'POST':
        student_form = studentForm(data=request.POST)
        student_extra_form = studentExtraForm(data=request.POST)

        
        if student_form.is_valid() and student_extra_form.is_valid():
            user = student_form.save()
            user.set_password(user.password)
            user.save()
            extra = student_extra_form.save(commit=False)
            extra.user = user
            extra.save()
            registered = True

        else:
            print(student_form.errors)

    else:
        upload_form = PdfForm()
        student_form=studentForm()
        student_extra_form = studentExtraForm()
        

    return render(request,'signup.html',{'student_form':student_form,'student_extra_form':student_extra_form,'registered':registered,'upload_form':upload_form,
    'userval':userval,'fullnameval':fullnameval,'percentileval':percentileval})

def updateCollegeDistance(myPin):
    print("Updating")
    for clg in CollegeModel.objects.all():
        clg.updateDistance(myPin)


def user_login(request):

    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                updateCollegeDistance(user.user_profile.pincode)
                return HttpResponseRedirect(reverse_lazy('landing'))
            else:
                return HttpResponseRedirect("ACCOUNT NOT ACTIVE")

        else:
            print("Someone Tried to login and failed")
            return HttpResponse("invalid login details supplied!")
    else:
        return render(request, 'login.html')


class CollegeListView(ListView):
    model = CollegeModel
    context_object_name = 'colleges'
    template_name = 'college_list.html'

    # def get_queryset(self):
    #     order = self.request.GET.get('orderby', '-beds')
    #     return Hospital.objects.order_by(order)

    def get_context_data(self, **kwargs):
        context = super(CollegeListView, self).get_context_data(**kwargs)

        d1 = self.request.GET.get('clb',0)
        d1 = int(d1)
        d2 = self.request.GET.get('cub', 100)
        d2 = int(d2)
        d3 = self.request.GET.get('dist', 1000)
        d3 = int(d3)

        context['clb'] = d1
        context['cub'] = d2
        context['dist'] = d3

        return context


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse_lazy('landing'))


def dataextract(request):
    name = request.FILES['file']
    doc = fitz.Document(name) 
    page = doc[0]
    print(page.get_text())


class CollegeDetailView(DetailView):
    model = CollegeModel
    template_name = 'college_detail.html'
    context_object_name = 'curr_college'

    # def get_context_data(self, **kwargs):
    #     # hosp_id = self.kwargs.get('pk')
    #     # hospital_curr = get_object_or_404(Hospital,pk=hosp_id)
    #     # print(hospital_curr.beds)
    #     print(self.request.user)
    #     context = super(HospitalDetailView, self).get_context_data(**kwargs)
    #     context['form'] = RequestForm
    #     return context

def collegeTourView(request):
    return render(request, 'tour.html')

class ChatbotView(TemplateView):
    template_name = "chatbot.html"

backend/api/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

    <title>{% block title %}{% endblock %} | InstiTour</title>
    {% block custom_styles %}{% endblock %}
  </head>
  <body>
    <nav class="navbar">
      <div class="nav-head">InstiTour</div>
      <div class="spacer text-white text-lg mx-10 font-semibold">
        {% if user.is_authenticated %} Hello {{ user.username }} {% endif %}
      </div>

      <div class="menu-links">
        <ul>
          <a href="{% url 'landing' %}"><li>Home</li></a>
          <a href="{% url 'chatbot_help' %}"><li>Chatbot</li></a>

          {% if user.is_authenticated %}
          <a href="{% url 'all_college' %}"><li>Search</li></a>
          <a href="{% url 'logout' %}"><li>Logout</li></a>

          {% else %}
          <a href="{% url 'login' %}"><li>Login</li></a>
          <a href="{% url 'create_user' %}"><li>Signup</li></a>

          {%endif%}
        </ul>
      </div>
    </nav>
    <script
      type="text/javascript"
      src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"
    ></script>

    <div id="google_translate_element" style="position:absolute; top:0; margin-left:380px; margin-top:8px;"></div>
    <script type="text/javascript">
      function googleTranslateElementInit() {
        new google.translate.TranslateElement(
          { pageLanguage: "en" },
          "google_translate_element"
        );
      }
    </script>

    {% block content %}{% endblock %} {% block custom_scripts %}{% endblock %}
  </body>
</html>

backend/api/templates/chatbot.html
{% extends 'base.html' %}

{% block title %} Helpdesk {% endblock %}
{% block custom_styles %}
    <link rel="stylesheet" href="https://npm-scalableminds.s3.eu-central-1.amazonaws.com/@scalableminds/chatroom@master/dist/Chatroom.css" />
{% endblock %}

{% block content %}
    <div class="chat-container"></div>
{% endblock %}


{% block custom_scripts %}
<script src="https://npm-scalableminds.s3.eu-central-1.amazonaws.com/@scalableminds/chatroom@master/dist/Chatroom.js"/></script>
<script type="text/javascript">
    var chatroom = new window.Chatroom({
    host: "http://localhost:5005",
    title: "Chat",
    container: document.querySelector(".chat-container"),
    welcomeMessage: "This is InstiTour Chat-Bot,how can i help you?",
    speechRecognition: "en-US",
    // voiceLang: "en-US"
    });
    chatroom.openChat();
</script>
{% endblock %}

backend/api/templates/college_detail.html
{% extends 'base.html' %}
{% block title %} {{curr_college.name}} {% endblock %}

{% block content %}

 <div class="college-desc">
    <div class="name">{{curr_college.name}}</div>
    <div class="address">Address - {{curr_college.address}}</div>
    <div class="pincode">Pincode - {{curr_college.pincode}}</div>
    <div class="cutoff">Cutoff - {{curr_college.cutoff}} Percentile</div>
    <div class="nirf-rank">NIRF Ranking: {{curr_college.nirf}}</div>

    {% if curr_college.hostel %}
        <div class="hostel">Hostel Available</div>
    {% else %}
        <div class="no-hostel">No Hostel</div>
    {% endif %}
    <div class="salary">Average Salary : {{curr_college.salary}}</div>
    <div class="website">Website: <a href="{{curr_collge.website}}">{{curr_college.website}}</a></div>
</div>

{% endblock %}

backend/api/templates/college_list.html
{% extends 'base.html' %}
{% block title %} Search {% endblock %}

{% block custom_styles  %}
<style>
    body{
        background-color: #8b86cc;
    }
</style>
{% endblock %}


{% block content %}




<form method="get" class="form-control" action="{% url "all_college" %}" class="cool-form my-4">
    <div class="form-container">
        <label for="clb">Cutoff Lower Bound</label>
        <input class="form-input" type="number" value={{clb}} placeholder="Cutoff" name="clb"/>
        <label for="cub">Cutoff Upper Bound</label>
        <input class="form-input" type="number" value={{cub}} name="cub"/>
        <label for="dist">Distance from you?(in km)</label>
        <input class="form-input" type="text" value={{dist}} name="dist" placeholder="Distance"/>   
        <input class="btn-submit form-input" type="submit" class="btn-submit form-input" name="submit" id="submit" value="Search" />
    </div>
</form>



{% for coll in colleges %}
    {% if coll.cutoff  >= clb and coll.cutoff <= cub and coll.distance <= dist %}
    <div class="college-card">
        <div class="flex flex-col">
            <div class="name">{{ coll.name }}</div>
            <div class="cutoff">Cut-off : {{ coll.cutoff }} Percentile</div>
        </div>
        <div class="flex-grow-[1]"></div>
        <div class="link-container">
            <a href="{% url "detail_college" pk=coll.pk %}">More Info</a>
            {% if coll.name == "Sardar Patel Institute of Technology" %}
                <a href="{% url "tour_college" %}">Virtual Tour</a>
            {% else %}
                <a disabled href="">Coming Soon</a>
            {% endif %}
        </div>
        <div class="distance">Distance: {{ coll.distance }} km</div>
    </div>
    {% endif %}
{% endfor %}


{% endblock %}

backend/api/templates/join.html
{% extends 'base.html' %}

{% block title %} Join In {% endblock %}

{% block custom_styles  %}
<style>
    body{
        background-color: #8b86cc;
    }
</style>
{% endblock %}


{% block content %}
<div class="flex flex-col hidden" id="reg-form">
    <form action="register" class="form-control" method="post">
        {% csrf_token %}
        <div class="form-container">
            <div class="flex">
                <input type="text" class="form-input rounded mr-1" name="fname" id="fname" placeholder="First Name" />
                <input type="text" class="form-input rounded ml-1" name="lname" id="lname" placeholder="Last Name" />    
            </div>
            <input type="email" class="form-input rounded" name="email" id="email" placeholder="Email Address"/>
            <input type="password" name="password" id="password" class="form-input" placeholder="Password" />
            <input type="number" class="form-input" name="percetile" id="percentile" placeholder="Percentile"/>
            <input type="text" name="address" id="address" class="form-input" placeholder="Address">
            <input type="number" class="form-input" name="pincode" id="pincode" placeholder="Pincode"/>
            <input type="submit" class="btn-submit form-input" name="submit" id="submit" value="Register" />
            <div class="text-center"> or <a href="#" id="alt-log" class="alt">Login</a></div>
        </div>
    </form>
</div>

<div class="flex" id="login-form">
    <form action="register" class="form-control flex-grow-[1]" method="post">
        <div class="form-container">
            <input type="email" class="form-input rounded" name="email" id="email" placeholder="Email Address"/>
            <input type="password" name="password" id="password" class="form-input" placeholder="Password" />
            <input type="submit" class="btn-submit form-input" name="submit" id="submit" value="Login" />
            <div class="text-center"> or <a href="#" id="alt-reg" class="alt"> Register</a></div>
        </div>
    </form>
    
</div>  
{% endblock %}

backend/api/templates/landing.html
{% extends 'base.html' %} {% block title %} Home {% endblock %} 


{% block content%}
<div class="college-cover">
  <div class="cover-mask">
    <h1>We help you find the right college for you</h1>
  </div>
</div>

<div class="content text-lg">
  <em>
  <p>
    Welcome to our educational institute finder <strong>InstiTour</strong>. Our
    application will provide you with some of the best possible college options
    avaliable to you based on your merit in the simplest possible way and a lot
    filtering parameters like cutoff , ranking , colleges near you and much
    more. You can either login and enter your details manually or use our unique
    document feature extraction and get the appropriate colleges just by
    uploading your marksheet.
  </p>

  <p class="text-center">
    Some other exiciting features of our application include 
    <div class="text-center text-xl"><strong>Custom Search</strong></div>
    <p class="text-center">
      Choose from multiple search filters to find out your ideal institute.
    </p>

    <div class="text-center text-xl"><strong>Virtual Reality Tour</strong></div>
    
    <p class="text-center">
      Get a fully fledged realistic experience of visiting campus of
      different colleges with th comfort of sitting at home with our virtual tour.
      Just select the college , and your ready to navigate through the campus with a
      simple and fun game with actual 360 view of the college campus
    </p>
     
    
    <div class="text-center text-xl"><strong>Chatbot</strong></div>
    
    <p class="text-center">
      No need to navigate through the UI to find different options Just ask the
      intelligent bot for something that is 24x7 avaliable to serve you We Hope that
      our application meets your expectations to fullfill most of your needs and you
      would like to visit again.
    </p>

  </p>
  </em>
  
</div>
{% endblock %}

backend/api/templates/login.html
{% extends 'base.html' %}

{% block title %} Log In {% endblock %}

{% block custom_styles  %}
<style>
    body{
        background-color: #8b86cc;
    }
</style>
{% endblock %}

{% block content  %}
<div class="flex" id="login-form">
  <form action="{% url 'login' %}" class="form-control flex-grow-[1]" method="post">
    {% csrf_token %}
    <div class="form-container">
        <input type="text" class="form-input rounded" name="username" id="username" placeholder="Username"/>
        <input type="password" name="password" id="password" class="form-input" placeholder="Password" />
        <input type="submit" class="btn-submit form-input" name="submit" id="submit" value="Login" />
        <div class="text-center"> or <a href="{% url 'create_user' %}" id="alt-reg" class="alt"> Register </a></div>
    </div>
  </form>
</div> 

{% endblock %}

backend/api/templates/signup.html
{% extends 'base.html' %}
{% block title %} Sign In {% endblock %}

{% block custom_styles  %}
<style>
    body{
        background-color: #8b86cc;
    }
</style>
{% endblock %}


{% block content %}

  <div class="flex flex-col" id="reg-form">
    {% if not registered %}

    <form action="." class="form-control" method="post" enctype="multipart/form-data">
      {%csrf_token%}  
      <div class="form-container">
        <label for="id_pdf" class="text-center">Upload CET Result</label><input type="file" class="form-input" name="pdf" id="pdf" />
        <input type="submit" class="btn-submit form-input" name="submit" id="submit" value="Upload" />
        <div class="text-center text-xl mb-2">OR</div>
        <div class="text-center">Enter Details</div>
        
        <input type="text" class="form-input rounded" name="name" id="email" value="{{fullnameval}}" placeholder="Name"/>
        <input type="text" class="form-input rounded" name="username" id="username"  placeholder="Username"/>
        <input type="email" class="form-input rounded" name="email" id="email" placeholder="Email Address"/>
        <input type="password" name="password" id="password" class="form-input" placeholder="Password" />
        <input type="number" class="form-input" name="percentile" id="percentile" value="{{percentileval}}" placeholder="Percentile"/>
        <input type="text" name="address" id="address" class="form-input" placeholder="Address">
        <input type="number" class="form-input" name="pincode" id="pincode" placeholder="Pincode"/>
        <input type="submit" class="btn-submit form-input" name="submit" id="submit" value="Register" />
        <div class="text-center"> or <a href="{% url 'login' %}" id="alt-log" class="alt">Login</a></div>
      </div>
    </form>
  </div>

{% else %}
  <div class="flex">
    <div class="form-control form-container text-center drop-shadow-lg mx-auto flex-row">
        Thank you for registering. You may <a href="{% url 'login' %}" class="underline mx-1"> login </a> Now!
    </div> 
  </div> 
{% endif %}
{% endblock %}

backend/api/templates/tour.html
{% extends 'base.html' %}

{% block title %} Virtual Tour {% endblock %}

{% load static %}

{% block custom_styles  %}
    <link
    rel="stylesheet"
    href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
    integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
    crossorigin=""
    />
    <!-- <style>
        body{
            background-color: #8b86cc;
        }
    </style> -->

{% endblock %}

{% block content %}
<div class="modal-wrapper hidden">
    <div class="modal">
      <button onclick="closeModal()">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>
      <div class="inst hidden">
        <p class="px-4 py-1">Use the arrow keys to move the character around to discover various viewpoints available.</p>
        <p class="px-4 py-1">Once you reach a checkpoint (Stop sign), press M to reveal the panoramic view</p>
      </div>
      <iframe
        class="mx-auto"
        src="https://momento360.com/e/u/be204b8cce24487c8ce1182de7b169bf?utm_campaign=embed&utm_source=other&heading=0&pitch=0&field-of-view=75&size=medium"
        frameborder="0"
        width="95%"
        height="580px"
      ></iframe>
    </div>
    <div class="backdrop"></div>
  </div>

  <div class="view">
      <div id="map-container" class="flex flex-col text-center">
        <div class="text-xl ml-24 mb-2"">Map</div>
        <div class="map ml-24" id="map"></div>
      </div>

      <div class="game">
          <div class="text-4xl mt-5 mb-5">Virtual Tour
            <button onclick="openModal(-1)">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            </button>
          </div>
          <div id="game-container"></div>
      </div>
  </div>

{% endblock %}

{% block custom_scripts %}
    <script
    src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
    integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
    crossorigin=""
    ></script>
    <script>
        let map = L.map("map").setView([19.123, 72.833], 15);
        let marker = L.marker([19.123, 72.833]).addTo(map);
        L.tileLayer(
        "https://api.maptiler.com/maps/basic/{z}/{x}/{y}.png?key=hwPAaLiIlgSZqqAt4lHt",
        {
            attribution:
            '<a href="https://www.maptiler.com/copyright/" target="_blank">&copy; MapTiler</a> <a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; OpenStreetMap contributors</a>',
        }
        ).addTo(map);
    </script>

    <script src="https://cdn.jsdelivr.net/npm/phaser@3.55.2/dist/phaser.js"></script>
    <script src="{% static 'js/script.js' %}"></script>

{% endblock %}